import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
    alignItems: 'center',
  },
  header: {
    padding: 16,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 16,
  },
  containerInfos: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  infoCard: {
    width: '48%',
    backgroundColor: '#192f53',
    borderRadius: 14,
    borderWidth: 1,
    padding: 14,
    borderColor: '#1f2f42',
  },
  cardLabel: {
    fontSize: 12.5,
    color: '#83898f',
    fontWeight: '600',
  },
  cardValue: {
    fontSize: 30,
    fontWeight: '800',
    color: '#E6EDF3',
  },
  cardDescription: {
    fontSize: 11,
    color: '#83898f',
  },
  veiculosContainer: {
    padding: 14,
    backgroundColor: '#192f53',
    width: '90%',
    borderRadius: 8, 
  },
  veiculosHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1000,
    marginLeft: 5,
    marginBottom: 17,
  },
  veiculosHeaderTitle: {
    position: 'static',
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    flex: 1,
  },
  dropdownFiltrar: {
    position: 'relative',
    minWidth: 100,
    alignItems: 'flex-end',
    zIndex: 1001,
  },
  textoSelecionado: {
    fontSize: 14,
    color: '#E6EDF3',
    fontWeight: 'bold',
    marginHorizontal: 4,
  },
  botaoSelecao: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#1E293B',
    borderRadius: 8,
    borderColor: '#ccc',
    minWidth: 110,
  },
  opcoesDropdown: {
    position: 'absolute',
    top: '115%',
    right: 0,
    backgroundColor: '#1E293B',
    borderRadius: 10,
    minWidth: 140,
    elevation: 10,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    overflow: 'scroll',
  },
  opcaoItem: {
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: '#1f2f42'
  },
  opcaoItemContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 12,
    height: 20,
  },
  opcaoItemText: {
    flexDirection: 'row',
    fontSize: 12,
    fontWeight: '500',
    color: '#E6EDF3',
  },
  opcaoSelecionada: {
    backgroundColor: '#1d478d',
    color: '#E6EDF3',
  },
  veiculosList: {
    alignItems: 'center',
    fontSize: 14,
    color: '#b8bfc7',
    marginBottom: 12,
    width: '100%',
  },
  veiculosCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#1E293B',
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginBottom: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: '#0b2b55',
  },
  veiculosInfo: {
    marginVertical: 4,
  },
  veiculosModelo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    fontSize: 14,
    color: '#E6EDF3',
    fontWeight: '600',
    marginVertical: 5,
  },
  veiculosPlaca: {
    fontSize: 14,
    color: '#E6EDF3',
    backgroundColor: '#334155',
    paddingHorizontal: 8,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    borderRadius: 8,
    overflow: 'hidden',
    marginBottom: 4,
  },
  veiculosKm: {
    fontSize: 11,
    color: '#83898f',
  },
  statusEBotaoLocalizar: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  veiculosStatus: {
    fontSize: 13,
    alignItems: 'flex-end',
    fontWeight: '600',
    color: '#22C55E',
    backgroundColor: '#22c55e26',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  botaoLocalizar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 27,
    backgroundColor: '#334155',
    borderWidth: 1,
    borderColor: 'transparent',
    gap: 3,
    paddingHorizontal: 5,
    paddingVertical: 4,
    borderRadius: 8,
  },
  textLocalizar: {
    fontSize: 13,
    color: '#E6EDF3',
  },
  footerVerMaisVeiculos: {
    padding: 12,
    alignItems: 'center',
  },
  verMaisVeiculos: {
    color: '#22C55E',
    fontSize: 14,
    fontWeight: '600',
    marginVertical: 10,
  },
  statusDisponivel: {
    backgroundColor: '#22c55e4d',
    color: '#22C55E',
  },
  statusAlugado: {
    color: '#3B82F6',
    backgroundColor: '#3b82f626',
  },
  statusManutencao: {
    backgroundColor: '#f59e0b26',
    color: '#F59E0B'
  }
})
