import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
    alignItems: "center",
  },
  headerListaDeContratos: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  containerDocumentos: {
    flexDirection: "column",
    paddingBottom: 18,
  },
  headerTitle: {
    marginTop: 0,
    fontSize: 22,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 6,
  },
  headerListaDeContatosDescricao: {
    color: "#83898f",
    fontSize: 14,
  },
  numeroDeContratos: {
    backgroundColor: "#22c55e2f",
    color: "#22C55E",
    height: 28,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingTop: 4,
    borderRadius: 12,
    textAlign: "center",
    fontSize: 14,
    fontWeight: "600",
  },
  containerListaDeContratos: {
    backgroundColor: "#192f53",
    padding: 14,
    width: "95%",
    borderRadius: 8,
    marginTop: 20,
  },
  listaDeContratosHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    zIndex: 1000,
    marginBottom: 17,
  },
  textoListaDeContratos: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fff",
  },
  filtrarContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    marginBottom: 12,
    zIndex: 1000,
  },

  dropdownFiltrar: {
    position: "relative",
    minWidth: 100,
    alignItems: "flex-end",
    zIndex: 1001,
  },
  botaoSelecao: {
    flexDirection: "row",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: "#1E293B",
    borderRadius: 8,
    borderColor: "#ccc",
    minWidth: 110,
  },
  textoSelecionado: {
    fontSize: 14,
    color: "#E6EDF3",
    fontWeight: "bold",
    marginHorizontal: 4,
  },
  opcoesDropdown: {
    position: "absolute",
    top: "115%",
    right: 0,
    backgroundColor: "#1E293B",
    borderRadius: 10,
    minWidth: 140,
    elevation: 10,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    overflow: "scroll",
  },
  opcaoItem: {
    padding: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2f42",
  },
  opcaoSelecionada: {
    backgroundColor: "#1d478d",
  },
  opcaoItemContent: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 12,
    height: 20,
  },
  opcaoItemText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#E6EDF3",
  },
  listaDeContratosCard: {
    backgroundColor: "#1E293B",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    marginBottom: 10,
    width: "100%",
    alignItems: "center",
  },
  contratosInfo: {
    flexDirection: "column",
    flex: 1,
  },
  tituloContrato: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
    gap: 8,
  },
  textoCliente: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  textoPlaca: {
    color: "#fff",
    backgroundColor: "#334155",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    fontSize: 12,
    overflow: "hidden",
  },
  descricaoContrato: {
    flexDirection: "column",
    gap: 2,
  },
  textoModelo: {
    color: "#83898f",
    fontSize: 14,
  },
  textoValor: {
    color: "#83898f",
    fontSize: 14,
  },
  textoVencimento: {
    color: "#EF4444",
    fontWeight: "600",
    fontSize: 13,
  },
  statusEBotaoFevolucao: {
    flexDirection: "column",
    alignItems: "flex-end",
  },
  statusPagamento: {
    color: "#F97316",
    fontWeight: "600",
    fontSize: 13,
    alignItems: "flex-end",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  botaoFinalizarDevolucao: {
    backgroundColor: "#334155",
    marginTop: 27,
    gap: 3,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 8,
  },
  textoBotaoFinalizar: {
    color: "#E6EDF3",
    fontWeight: "600",
    fontSize: 14,
  },
  statusPendente: {
    color: "#F97316",
    backgroundColor: "#f59e0b26",
  },
  statusPago: {
    color: "#22C55E",
    backgroundColor: "#22c55e26",
  },
  statusAtrasado: {
    color: "#EF4444",
    backgroundColor: "#ef444426",
  },
  statusRecusado: {
    color: "#EF4444",
    backgroundColor: "#ef444426",
  },
  statusCancelado: {
    color: "#EF4444",
    backgroundColor: "#ef444426",
  },
});
