

services:
  # 1. Banco de Dados (MySQL)
  db:
    image: mysql:8
    container_name: motoriz_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 2. Backend (Spring Boot) — sem portas expostas externamente
  backend:
    build: ./backend
    container_name: motoriz_backend
    ports:
      - "8080:8080"
    environment:
      # DB_HOST: db
      # DB_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      # AWS_REGION: ${AWS_REGION}
      # AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  mobile:
    build: ./mobile
    container_name: motoriz_mobile
    ports:
      - "8081:8081"
    volumes:
      - ./mobile/MotorizApp:/app
    environment: 
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysqldata:

networks:
  app-network:
    driver: bridge
